---

layout: post

title: promise

subtitle: SEB TIL

categories: coding

tags: [javascript]

---
# Promise

<aside>
함수는 내부의 처리 양이나 순서에 따라 반환되는 시점이나 코드가 동작하는 타이밍이 제각각이다. 함수가 처리될 때 까지 매번 호출하는 것은 비효율 적이므로 함수의 각 상태에 따라 동작을 정해주면 어떨까?

</aside>

```jsx
const pr = new Promise((resolve, reject) => {
    // code
});
```

<aside>
`Promise` 의 기본 사용법은 위 코드와 같다. 객체를 생성하고 각 상태에 따른 파라미터 함수를 넣어준다. 여기서 첫 번째 인자 `resolve` 는 성공적으로 동작했을 때 호출되는 함수, `reject` 는 실패 시 호출되는 함수를 정의한다.

그리고 이처럼 어떠한 동작이후 호출되는 함수를 `callback` 함수라고 부른다.

</aside>

![Untitled](/post-img/promise01.png)

<aside>
`promise` 객체는 state와 result 프로퍼티를 가지고 있다. 각 상태에 따라 위 사진과 같이 할당하게 된다.

</aside>

```jsx
const gun = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('shoot!');
    }, 2000);
});

gun.then(
    function resolve(result) {
        console.log(result);
    }
);
```

<aside>
간단하게 2초 후 실행되는 함수를 `promise` 안에 넣어 보았다. 

`then` 은 `promise` 객체의 상태별 생동을 선언하는 구간으로 현재는 성공상태인 `resolve` 를 구현해 놓았다. 결과적으로 2초후 성공적으로 함수가 실행되면 `'shoot!'` 으로 넣은 파라미터가 result 값으로 전달되어 출력된다.

</aside>

```jsx
const gun = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('shoot!');
    }, 2000);
});

gun.then(
    function resolve(result) {
        console.log(result);
    },

    function reject(err) { 
        console.log('Error!');
     }
);
```

<aside>
`reject` 를 선언해도 함수가 실패하지 않는다면 호출되지 않는다.

</aside>

```jsx
const gun = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('shoot!');
    }, 2000);
});

gun.then(
    function resolve(result) {
        console.log(result);
    }
).catch(
    function reject(err) {
        console.log(err);
    }
).finally(
		function() {
				console.log('gun end');
		}
);
```

<aside>
혹은 실패상태인 `reject` 를 catch 구간에 넣을 수 있다. 이런식으로 구현한다면 `then` 내부에서 에러가 발생해도 제어가 가능해지고 가독성 또한 좋아진다.

`finally` 는 최종 상태를 가리지 않고 무조건 최종적으로 실행되는 구간이다. 로딩화면과 같은 중간과정을 처리할 때 자주 사용된다.

</aside>

```jsx
const f1 = (callback) => {
    setTimeout(function() {
        console.log('first func');
        callback();
    }, 1000);
};

const f2 = (callback) => {
    setTimeout(function() {
        console.log('second func');
        callback();
    }, 3000);
};

const f3 = (callback) => {
    setTimeout(function() {
        console.log('third func');
        callback();
    }, 2000);
};

console.log('start!');
f1(function() {
    f2(function() {
        f3(function() {
            console.log('the end!');
        })
    })
});
```

<aside>
만약 `Promise` 를 사용하지 동기적으로 처리 한다면 다음과 같을 것이다. 매 함수별로 지정된 시간을 기다리고 각 함수내부에서 다음 함수를 호출하며 깊이가 비정상적으로 깊어지는데 이렇게 `callback` 함수가 연쇄적으로 호출되며 깊어지는 것을 `CallBack Hell` 말 그대로 콜백의 지옥이라는 뜻으로 부른다.

</aside>

```jsx
const f1 = () => {
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('first success!');
        }, 1000);
    });
};

const f2 = (msg) => {
    console.log(msg);
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('second success!');
        }, 3000);
    });
};

const f3 = (msg) => {
    console.log(msg);
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('third success!');
        }, 2000);
    });
};

f1()
.then(res => f2(res))
.then(res => f3(res))
.then(res => console.log(res))
.catch(console.log)
.finally(() => {
    console.log('End!');
});
```

<aside>
위 처럼 `Promise` 를 사용해 정리해 보았다. 이전 콜백 함수를 사용하던 때보다 확실히 가독성이 높아졌다.

</aside>

```jsx
const f1 = () => {
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('first success!');
        }, 1000);
    });
};

const f2 = (msg) => {
    console.log(msg);
    return new Promise((res, rej) => {
        setTimeout(() => {
            rej("xxx");
        }, 3000);
    });
};

const f3 = (msg) => {
    console.log(msg);
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('third success!');
        }, 2000);
    });
};

f1()
.then(res => f2(res))
.then(res => f3(res))
.then(res => console.log(res))
.catch(console.log)
.finally(() => {
    console.log('End!');
});
```

<aside>
만약 두번째 함수에서 `reject` 함수를 지정해 에러를 발생시키면 어떻게 될까? 

이 코드는 두번째 함수에서 에러를 받아 `catch` 로 넘어가고 곧바로 `finally` 로 넘어간다.

</aside>

## Promise.all

```jsx
const f1 = () => {
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('first success!');
        }, 1000);
    });
};

const f2 = (msg) => {
    console.log(msg);
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('second success!');
        }, 3000);
    });
};

const f3 = (msg) => {
    console.log(msg);
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('third success!');
        }, 2000);
    });
};

console.time('x');
Promise.all([f1(), f2(), f3()])
.then(res => {
    console.log(res);
    console.timeEnd('x');
});
```

<aside>
기존의 코드들은 각 함수를 순환하며 처리를 기다리고 다음 순차를 실행하였지만 `Promise.all()` 은 실행할 함수들을 한꺼번에 받아들여 처리한다. 

실제 `console.time` 을 활용해 시간을 체크해 보면 보다 빠르게 동작하는 것을 볼 수 있다. 하지만 `reject` 가 호출될 경우 실행에 성공한 함수의 값도 건너 뛰기 때문에 사용에 주의해야 한다.

</aside>

## Promise.race

```jsx
const f1 = () => {
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('first success!');
        }, 1000);
    });
};

const f2 = (msg) => {
    console.log(msg);
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('second success!');
        }, 3000);
    });
};

const f3 = (msg) => {
    console.log(msg);
    return new Promise((res, rej) => {
        setTimeout(() => {
            res('third success!');
        }, 2000);
    });
};

console.time('x');
Promise.race([f1(), f2(), f3()])
.then(res => {
    console.log(res);
    console.timeEnd('x');
});
```

<aside>
`Promise.race()` 는 말 그대로 경주를 시키는 함수이다. 사용법은 `Promise.all()` 과 비슷하지만 배열내 함수 중 하나라도 실행이 완료되면 전체 종료가 이뤄진다. 

특히 용량이 큰 이미지나 파일을 렌더링할 때 시각적으로 빠른 표현을 위해 이러한 함수를 주로 사용한다.

</aside>

---

<br><br><br>



## 참고 사이트
- [제로초 Blog](https://www.zerocho.com/category/JavaScript/post/5b0645cc7e3e36001bf676eb)
